Creatives_CSharp/Creatives/Models/Art.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Creatives.Models;

public class Art
{

    // ================
    // Art ID
    // ================
    [Key]
    public int ArtId { get; set; }

    // ================
    // Name
    // ================
    [Required(ErrorMessage=" is required!")]
    public string Name { get; set; }

    // ================
    // Artist
    // ================
    [Required(ErrorMessage=" is required!")]
    public string Artist { get; set; }
    
    // ================
    // Description
    // ================
    [Required(ErrorMessage=" is required!")]
    public string Description { get; set; }
    
    // ================
    // Price
    // ================
    [Required(ErrorMessage="Price is required!")]
    public double Price { get; set; }

    // ================
    // CreatedAt
    // ================
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    // ================
    // UpdatedAt
    // ================
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    //! ===================================
    //! Relationships
    //! ===================================
    // ================
    // User - One to Many
    // ================
    public int UserId { get; set; }
    public User? Poster { get; set; }
    
    // ================
    // Likes - Many to Many
    // ================
    public List<Like> Followers { get; set; } = new List<Like>();
}

Creatives_CSharp/Creatives/Controllers/ArtController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Creatives.Models;

public class ArtController : Controller
{
    // ===========
    // Getting User ID
    // ===========
    private int? uid
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    // ===========
    // Getting Logged In User
    // ===========
    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }


    // ===========
    // Accesing Database for Manipulation
    // ===========
    private CreativesContext db;
    public ArtController(CreativesContext context)
    {
        db = context;
    }

    // ================
    // Dashboard
    // ================
    [HttpGet("/dashboard")]
    public IActionResult Dashboard(string search)
    {
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Welcome", "User");
        }

        if(search != null)
        {
            List<Art> filteredArt = db.Arts
                .Include(a => a.Poster)
                .Include(a => a.Followers)
                .Where(a => a.Artist.Contains(search)
                    || a.Name.Contains(search))
                .ToList();
            return View("Dashboard", filteredArt);
            
        }

        // ========
        // Get All Art
        // ========
        List<Art> allArt = db.Arts
            .Include(a => a.Poster)
            .Include(a => a.Followers)
            .ToList();



        return View("Dashboard", allArt);
    }

    // ================
    // New Art Render
    // ================
    [HttpGet("/art/new")]
    public IActionResult New()
    {
        if(!loggedIn)
        {
            return RedirectToAction("Welcome", "User");
        }
        return View("NewArt");
    }

    // ================
    // New Art Post
    // ================
    [HttpPost("/art/create")]
    public IActionResult CreateArt(Art newArt)
    {
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Index", "Users");
        }

        
        if(!ModelState.IsValid)
        {
            Console.WriteLine("======================");
            Console.WriteLine("Invalid!!!!");
            Console.WriteLine("======================");

            return New();
            }

        newArt.UserId = (int)uid;

        db.Arts.Add(newArt);
        db.SaveChanges();
        return RedirectToAction("Dashboard");
    }

    // ================
    // View Art Render
    // ================
    [HttpGet("/art/{artId}/view")]
    public IActionResult ViewArt(int artId)
    {

        if(!loggedIn)
        {
            return RedirectToAction("Welcome", "User");
        }

        // find the id
        Art? art = db.Arts.FirstOrDefault(p => p.ArtId == artId);

        // if id not found
        if(art == null)
        {
            return RedirectToAction("Dashboard");
        }

        return View("ViewArt", art);
    }

    // ================
    // Edit Art Render
    // ================
    [HttpGet("/art/{artId}/edit")]
    public IActionResult EditArt(int artId)
    {

        if(!loggedIn)
        {
            return RedirectToAction("Welcome", "User");
        }

        // find the id
        Art? art = db.Arts.FirstOrDefault(p => p.ArtId == artId);

        // if id not found
        if(art == null)
        {
            return RedirectToAction("Dashboard");
        }

        return View("EditArt", art);
    }

    // =======================
    // Edit Art Post
    // =======================
    [HttpPost("/art/{artId}/update")]
    public IActionResult UpdateArt(Art editedArt, int artId)
    {
        if(!loggedIn)
        {
            return RedirectToAction("Welcome", "User");
        }   
        
        if(!ModelState.IsValid)
        {   
            return EditArt(artId);
        }

        // does the art exist?
        Art? dbArt = db.Arts.FirstOrDefault(p => p.ArtId == artId);
        if(dbArt == null)
        {   
            return RedirectToAction("Dashboard");
        }

        dbArt.Name = editedArt.Name;
        dbArt.Artist = editedArt.Artist;
        dbArt.Description = editedArt.Description;
        dbArt.Price = editedArt.Price;
        dbArt.UpdatedAt = DateTime.Now;

        db.Arts.Update(dbArt);
        Console.WriteLine("====***********************=====");
        db.SaveChanges();


        return RedirectToAction("Dashboard");
    }

    // =======================
    // Delete Art
    // =======================
    [HttpPost("/art/{deletedArtId}/delete")]
    public IActionResult DeleteArt(int deletedArtId)
    {
        if(!loggedIn) {
            return RedirectToAction("Welcome", "User");
        }

        Art? art = db.Arts.FirstOrDefault(a => a.ArtId == deletedArtId);

        if(art != null)
        {
            db.Arts.Remove(art);
            db.SaveChanges();
        }

        return RedirectToAction("Dashboard");

    }

    // =======================
    // Like Art
    // =======================
    [HttpPost("/art/{artId}/like")]
    public IActionResult Like(int artId)
    {
        
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Welcome", "User");
        }   

    Like? existingLike = db.Likes
        .FirstOrDefault(l => l.ArtId == artId && l.UserId == (int) uid);

    if(existingLike == null)
    {
        Like newLike = new Like()
        {
            UserId = (int)uid,
            ArtId = artId
        };
        db.Likes.Add(newLike);
    }
    else
    {
        db.Likes.Remove(existingLike);
    }

    db.SaveChanges();

    return RedirectToAction("Dashboard");
    }

}

Creatives_CSharp/Creatives/Views/Art/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
@model List<Art>


<div class="container">
    <h2 class="text-center">All Art</h2>

    <form
        asp-controller="Art"
        asp-action="Dashboard"
        method="GET"
    >
        <div class="d-flex justify-content-center gap-3 mb-3">
            <input type="text" class="form-control w-50" name="search" placeholder="search..">
            <button class="text-primary bg-transparent border-0 p-0">search</button>
        </div>
    </form>

    <table class="d-flex flex-column ">
        <thead>
            <tr class="d-flex border">
                <th class="w-50 text-center">Name</th>
                <th class="w-50 text-center">Artist</th>
                <th class="w-50 text-center">Description</th>
                <th class="w-50 text-center">Price</th>
                <th class="w-50 text-center d-flex justify-content-center align-items-center gap-3">
                    <div>Total Likes</div>
                    <form
                        asp-controller="Art"
                        asp-action="Dashboard"
                        method="GET"
                    >
                        <input type="hidden" class="form-control w-50" name="totalLikes" value="true">
                        <button class="text-primary bg-transparent border-0 p-0">^</button>
                    </form>
                </th>
                <th class="w-50 text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Art a in Model)
            {
                <tr class="d-flex justify-content-center w-100 border">
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center">
                        <a href="/art/@a.ArtId/view">@a.Name</a>
                    </td>
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center">@a.Artist</td>
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center">@a.Description</td>
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center">$@a.Price</td>
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center gap-3">
                        <div>@a.Followers.Count</div>
                    </td>
                    <td class="w-50 text-center border d-flex justify-content-center align-items-center" class="d-flex gap-2">
                        @if(a.UserId == Context.Session.GetInt32("UUID"))
                        {
                            <form
                                asp-controller="Art"
                                asp-action="DeleteArt"
                                asp-route-deletedArtId="@a.ArtId"
                                method="POST">
                                <button class="text-danger bg-transparent border-0 p-0">Delete</button>
                            </form>
                            <a href="/art/@a.ArtId/edit" class="text-warning text-decoration-none">Edit</a>
                        }
                        
                        @{ bool alreadyLiked = a.Followers.Any(likes => likes.UserId == Context.Session.GetInt32("UUID"));}
                        <form
                            asp-controller="Art"
                            asp-action="Like"
                            asp-route-artId="@a.ArtId"
                            method="POST"
                        >
                            <button class="text-primary bg-transparent border-0 p-0">
                                @if(alreadyLiked)
                                {
                                    <span>Unlike</span>
                                }
                                else {
                                    <span>Like</span>
                                }
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Creatives_CSharp/Creatives/Views/Art/EditArt.cshtml
@model Art
@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h2>Edit Art</h2>

    <form
        class="shadow p-3 rounded"
        asp-controller="Art"
        asp-action="UpdateArt"
        asp-route-artId="@Model.ArtId"
        method="POST">

        <div class="mb-3">
            <label asp-for="@Model.Name"></label>
            <span asp-validation-for="@Model.Name" class="text-danger font-weight bold"></span>
            <input asp-for="@Model.Name" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Artist"></label>
            <span asp-validation-for="@Model.Artist" class="text-danger font-weight bold"></span>
            <input asp-for="@Model.Artist" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description"></label>
            <span asp-validation-for="@Model.Description" class="text-danger font-weight bold"></span>
            <input asp-for="@Model.Description" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price"></label>
            <span asp-validation-for="@Model.Price" class="text-danger font-weight bold"></span>
            <input asp-for="@Model.Price" type="number" class="form-control"/>
        </div>
        <button class="btn btn-success">Edit!</button>
    </form>
</div>

Creatives_CSharp/Creatives/Views/Art/NewArt.cshtml
@model Art


<div class="container">
    <h2>New Art</h2>

    <form
        class="shadow p-3 rounded"
        asp-controller="Art"
        asp-action="CreateArt"
        method="POST">

        <div class="mb-3">
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger font-weight bold"></span>
            <input asp-for="Name" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Artist"></label>
            <span asp-validation-for="Artist" class="text-danger font-weight bold"></span>
            <input asp-for="Artist" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <span asp-validation-for="Description" class="text-danger font-weight bold"></span>
            <input asp-for="Description" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Price"></label>
            <span asp-validation-for="Price" class="text-danger font-weight bold"></span>
            <input asp-for="Price" type="number" class="form-control"/>
        </div>
        <button class="btn btn-success">Add!</button>
    </form>
</div>

Creatives_CSharp/Creatives/Views/Art/ViewArt.cshtml
@model Art
@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h2>@Model.Name</h2>
    <h2>By: @Model.Artist</h2>
    <p>@Model.Description</p>
    <p>@Model.Price</p>
    
</div>